# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PassCli < Formula
  desc "Secure, cross-platform CLI password and API key manager for developers"
  homepage "https://github.com/reyamira/pass-cli"
  version "0.17.21"
  license "MIT"

  on_macos do
    url "https://github.com/reyamira/pass-cli/releases/download/v0.17.21/pass-cli_0.17.21_darwin_all.tar.gz"
    sha256 "9478721cd897bf590a2f1282095200b38b3648bae98dd9ad8cdc03cbe755d058"

    def install
      bin.install "pass-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/reyamira/pass-cli/releases/download/v0.17.21/pass-cli_0.17.21_linux_x86_64.tar.gz"
      sha256 "d272f38f2417736746ba580a07facd67e86f8d4d642bf9e7cc58f5cd79ed245f"
      def install
        bin.install "pass-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reyamira/pass-cli/releases/download/v0.17.21/pass-cli_0.17.21_linux_arm64.tar.gz"
      sha256 "db01069aa8c1c7c74cc1803a74bf7dfce6f2e72471d1308cdaf050623056d6ed"
      def install
        bin.install "pass-cli"
      end
    end
  end

  def caveats
    <<~EOS
      Pass-CLI: Secure password manager with TUI and CLI interfaces

      First-time users: Run `pass-cli` (no arguments) for guided setup.

      Quick start:
        pass-cli          - Launch interactive TUI
        pass-cli init     - Initialize vault manually
        pass-cli doctor   - Run health checks

      Features:
        • Interactive TUI for visual management
        • Keychain integration: pass-cli keychain enable
        • Usage tracking and audit logging

      Vault location: ~/.pass-cli/vault.enc
      Complete guide: https://github.com/reyamira/pass-cli/blob/main/docs/GETTING_STARTED.md
    EOS
  end

  test do
    system "#{bin}/pass-cli", "version"
  end
end
