# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PassCli < Formula
  desc "Secure, cross-platform CLI password and API key manager for developers"
  homepage "https://github.com/reyamira/pass-cli"
  version "0.19.0"
  license "MIT"

  on_macos do
    url "https://github.com/reyamira/pass-cli/releases/download/v0.19.0/pass-cli_0.19.0_darwin_all.tar.gz"
    sha256 "2ae983854bb7c3faaf238eba229f3ff91cf6b1d16e3e226eeab4378194f489a3"

    define_method(:install) do
      bin.install "pass-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/reyamira/pass-cli/releases/download/v0.19.0/pass-cli_0.19.0_linux_x86_64.tar.gz"
      sha256 "5447b5d6b3c629bb8d2bffe5b8638dd82f48d7e2c908ed1999a035f9141449f3"
      define_method(:install) do
        bin.install "pass-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reyamira/pass-cli/releases/download/v0.19.0/pass-cli_0.19.0_linux_arm64.tar.gz"
      sha256 "50bc18cfeeca128a01a0da9c004bc4c4b5670c055194dab675d216a916485069"
      define_method(:install) do
        bin.install "pass-cli"
      end
    end
  end

  def caveats
    <<~EOS
      Pass-CLI: Secure password manager with TUI and CLI interfaces

      First-time users: Run `pass-cli` (no arguments) for guided setup.

      Quick start:
        pass-cli          - Launch interactive TUI
        pass-cli init     - Initialize vault manually
        pass-cli doctor   - Run health checks

      Features:
        • Interactive TUI for visual management
        • Keychain integration: pass-cli keychain enable
        • Usage tracking and audit logging

      Vault location: ~/.pass-cli/vault.enc
      Complete guide: https://github.com/reyamira/pass-cli/blob/main/docs/GETTING_STARTED.md
    EOS
  end

  test do
    system "#{bin}/pass-cli", "version"
  end
end
