# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PassCli < Formula
  desc "Secure, cross-platform CLI password and API key manager for developers"
  homepage "https://github.com/reyamira/pass-cli"
  version "0.18.0"
  license "MIT"

  on_macos do
    url "https://github.com/reyamira/pass-cli/releases/download/v0.18.0/pass-cli_0.18.0_darwin_all.tar.gz"
    sha256 "6c870b74332f2ac21976f9b78001c0fa5be56026200983d488219f7994957d0d"

    define_method(:install) do
      bin.install "pass-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/reyamira/pass-cli/releases/download/v0.18.0/pass-cli_0.18.0_linux_x86_64.tar.gz"
      sha256 "7a96c777374a13f194a06b4b1a27c93dc4888ed2d37a71fdfc2c951465e04a4d"
      define_method(:install) do
        bin.install "pass-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reyamira/pass-cli/releases/download/v0.18.0/pass-cli_0.18.0_linux_arm64.tar.gz"
      sha256 "dde208736c4378c0563d630a0e9d80e14a956764dedb8ef3456f6bde272d626c"
      define_method(:install) do
        bin.install "pass-cli"
      end
    end
  end

  def caveats
    <<~EOS
      Pass-CLI: Secure password manager with TUI and CLI interfaces

      First-time users: Run `pass-cli` (no arguments) for guided setup.

      Quick start:
        pass-cli          - Launch interactive TUI
        pass-cli init     - Initialize vault manually
        pass-cli doctor   - Run health checks

      Features:
        • Interactive TUI for visual management
        • Keychain integration: pass-cli keychain enable
        • Usage tracking and audit logging

      Vault location: ~/.pass-cli/vault.enc
      Complete guide: https://github.com/reyamira/pass-cli/blob/main/docs/GETTING_STARTED.md
    EOS
  end

  test do
    system "#{bin}/pass-cli", "version"
  end
end
